<?php

namespace GalleryBundle\Entity;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlbumForMainPage()
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = "SELECT album_id
                FROM album_image
                GROUP BY album_id
                HAVING COUNT(image_id) < 10";
        $statement = $connection->prepare($sql);
        $statement->execute();
        $almubIdsMass = $statement->fetchAll();

        $albumIdsString = '(';
        foreach($almubIdsMass as $album)
        {
            $albumIdsString .= $album['album_id'].',';
        }
        $albumIdsString = trim($albumIdsString, ',').')';

        $sql = "SELECT a.*, i.url
                FROM album a 
                INNER JOIN album_image ai ON (a.id = ai.album_id AND a.id IN ".$albumIdsString.")
                INNER JOIN image i ON (i.id = ai.image_id)";
        $statement = $connection->prepare($sql);
        $statement->execute();
        $smallAlbums = $statement->fetchAll();

        $sql = "SELECT a.id, a.name, i.url
                FROM album a 
                INNER JOIN image i ON (i.id = a.cover AND a.id NOT IN ".$albumIdsString.")";
        $statement = $connection->prepare($sql);
        $statement->execute();
        $bigAlbums = $statement->fetchAll();

        return array('small' => $smallAlbums, 'big' => $bigAlbums);
    }
}
